name: Build

on:
  push:
    branches:
      - "master"
    paths:
      - "LegacyBossBar/src/main/java/**/*.java"
      - "LegacyBossBar/src/main/resources/plugin.yml"
      - "Prohibition/src/main/java/**/*.java"
      - "Prohibition/src/main/resources/config.yml"
      - "Prohibition/src/main/resources/plugin.yml"
      - "Prohibition/src/main/resources/META-INF/services"
      - "VIPTickets/src/main/java/**/*.java"
      - "VIPTickets/src/main/resources/config.yml"
      - "VIPTickets/src/main/resources/plugin.yml"
      - "VoidDummy/src/main/java/**/*.java"
      - "VoidDummy/src/main/resources/plugin.yml"
      - "**/pom.xml"
      - "!.gitignore"
      - "!COPYING"
  pull_request:
    branches:
      - "master"
    paths:
      - "LegacyBossBar/src/main/java/**/*.java"
      - "LegacyBossBar/src/main/resources/plugin.yml"
      - "Prohibition/src/main/java/**/*.java"
      - "Prohibition/src/main/resources/config.yml"
      - "Prohibition/src/main/resources/plugin.yml"
      - "Prohibition/src/main/resources/META-INF/services"
      - "VIPTickets/src/main/java/**/*.java"
      - "VIPTickets/src/main/resources/config.yml"
      - "VIPTickets/src/main/resources/plugin.yml"
      - "VoidDummy/src/main/java/**/*.java"
      - "VoidDummy/src/main/resources/plugin.yml"
      - "**/pom.xml"
      - "!.gitignore"
      - "!COPYING"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java-version: [ 8, 11, 17, 21, 25 ]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: corretto
          cache: maven

      - name: Build
        run: mvn -B -V -e -ntp -Dstyle.color=always clean verify

      - name: Upload artifacts
        if: ${{ (github.ref_name == 'master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v5
        with:
          name: Gadgets-${{ github.run_id }}-${{ matrix.os }}-java-${{ matrix.java-version }}
          path: |
            LegacyBossBar/target/*.jar
            Prohibition/target/*.jar
            VIPTickets/target/*.jar
            VoidDummy/target/*.jar
          retention-days: 1
          overwrite: true